# Generated by Django 2.1.1 on 2020-01-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appreviation', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('lob', models.CharField(max_length=30)),
            ],
        ),
    ]
