# Generated by Django 2.1.1 on 2020-03-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('creator_on_prem', models.BooleanField(default=False)),
                ('explorer_on_prem', models.BooleanField(default=False)),
                ('viewer_on_prem', models.BooleanField(default=False)),
                ('term_desktop_personal', models.BooleanField(default=False)),
                ('term_desktop_professional', models.BooleanField(default=False)),
                ('term_server_core', models.BooleanField(default=False)),
                ('term_server_interactor', models.BooleanField(default=False)),
                ('tableau_online', models.BooleanField(default=False)),
                ('server_management', models.BooleanField(default=False)),
                ('creator_online', models.BooleanField(default=False)),
                ('explorer_online', models.BooleanField(default=False)),
                ('viewer_online', models.BooleanField(default=False)),
                ('perpetual_desktop_personal', models.BooleanField(default=False)),
                ('perpetual_desktop_professinal', models.BooleanField(default=False)),
                ('perpetual_server_core', models.BooleanField(default=False)),
                ('perpetual_server_interactor', models.BooleanField(default=False)),
                ('data_management_online', models.BooleanField(default=False)),
                ('data_management_on_premise', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal_app.Deal')),
            ],
        ),
        migrations.CreateModel(
            name='Deal_Items_Price_Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='deal_items',
            name='deal_price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deal_app.Deal_Items_Price_Lookup'),
        ),
    ]
