# Generated by Django 2.1.1 on 2020-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0002_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='name',
            field=models.CharField(default='mO', max_length=20),
        ),
    ]
